### PR TITLE
feat: add fonts-femkeklaver

### PR DESCRIPTION
**Pull request by Udacv**
Fonts-femkeklaver is a simple handwriting font with strong repeated tracing.

Log: add fonts-femkeklaver
Issue: deepin-community/sig-deepin-sysdev-team#219

### CODE REVIEW

**Comment by Udacv** [comment]
@chenchongbiao

**Comment by Udacv** [comment]
@chenchongbiao 请学长查看

**Comment by Udacv** [comment]
@chenchongbiao

**Review by chenchongbiao — APPROVED** [review]

**Pull request merged**
